/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  anon_sym_EQ_EQ = 3,
  anon_sym_BANG_EQ = 4,
  anon_sym_GT = 5,
  anon_sym_LT = 6,
  anon_sym_GT_EQ = 7,
  anon_sym_LT_EQ = 8,
  anon_sym_STAR_STAR = 9,
  anon_sym_STAR = 10,
  anon_sym_SLASH = 11,
  anon_sym_SLASH_SLASH = 12,
  anon_sym_PERCENT = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_isnot = 16,
  anon_sym_is = 17,
  anon_sym_and = 18,
  anon_sym_AMP_AMP = 19,
  anon_sym_or = 20,
  anon_sym_PIPE_PIPE = 21,
  anon_sym_BANG = 22,
  anon_sym_not = 23,
  anon_sym_LPAREN = 24,
  anon_sym_RPAREN = 25,
  sym_string_literal = 26,
  sym_integer_literal = 27,
  sym_float_literal = 28,
  sym__identifier_regexp = 29,
  anon_sym_AT = 30,
  anon_sym_COLON_COLON = 31,
  sym_source_file = 32,
  sym__node = 33,
  sym_expression_block = 34,
  sym_comparison_operators = 35,
  sym__expression = 36,
  sym__primary_expression = 37,
  sym_binary_expression = 38,
  sym_comparison_expression = 39,
  sym_equality_expression = 40,
  sym_identity_expression = 41,
  sym_logical_expression = 42,
  sym_unary_expression = 43,
  sym_parenthesized_expression = 44,
  sym__number_literal = 45,
  sym__identifier = 46,
  sym_user_identifier = 47,
  sym_namespace_name = 48,
  sym_namespace_value = 49,
  sym_namespace_identifier = 50,
  aux_sym_source_file_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_SLASH_SLASH] = "//",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_isnot] = "is not",
  [anon_sym_is] = "is",
  [anon_sym_and] = "and",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_or] = "or",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_BANG] = "!",
  [anon_sym_not] = "not",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_string_literal] = "string_literal",
  [sym_integer_literal] = "integer_literal",
  [sym_float_literal] = "float_literal",
  [sym__identifier_regexp] = "_identifier_regexp",
  [anon_sym_AT] = "@",
  [anon_sym_COLON_COLON] = "::",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym_expression_block] = "expression_block",
  [sym_comparison_operators] = "comparison_operators",
  [sym__expression] = "_expression",
  [sym__primary_expression] = "_primary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_comparison_expression] = "comparison_expression",
  [sym_equality_expression] = "equality_expression",
  [sym_identity_expression] = "identity_expression",
  [sym_logical_expression] = "logical_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym__number_literal] = "_number_literal",
  [sym__identifier] = "_identifier",
  [sym_user_identifier] = "user_identifier",
  [sym_namespace_name] = "namespace_name",
  [sym_namespace_value] = "namespace_value",
  [sym_namespace_identifier] = "namespace_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_isnot] = anon_sym_isnot,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_string_literal] = sym_string_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_float_literal] = sym_float_literal,
  [sym__identifier_regexp] = sym__identifier_regexp,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym_expression_block] = sym_expression_block,
  [sym_comparison_operators] = sym_comparison_operators,
  [sym__expression] = sym__expression,
  [sym__primary_expression] = sym__primary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_comparison_expression] = sym_comparison_expression,
  [sym_equality_expression] = sym_equality_expression,
  [sym_identity_expression] = sym_identity_expression,
  [sym_logical_expression] = sym_logical_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym__number_literal] = sym__number_literal,
  [sym__identifier] = sym__identifier,
  [sym_user_identifier] = sym_user_identifier,
  [sym_namespace_name] = sym_namespace_name,
  [sym_namespace_value] = sym_namespace_value,
  [sym_namespace_identifier] = sym_namespace_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isnot] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier_regexp] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_block] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operators] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__primary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_equality_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identity_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__number_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_user_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_name] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_value] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_namespace_prefix = 2,
  field_namespace_separator = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_namespace_prefix] = "namespace_prefix",
  [field_namespace_separator] = "namespace_separator",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_namespace_prefix, 0},
  [2] =
    {field_name, 1},
    {field_namespace_separator, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '!', 48,
        '"', 3,
        '%', 38,
        '&', 4,
        '\'', 5,
        '(', 51,
        ')', 52,
        '*', 35,
        '+', 39,
        '-', 40,
        '/', 36,
        ':', 6,
        '<', 31,
        '=', 8,
        '>', 30,
        '@', 59,
        'a', 10,
        'i', 15,
        'n', 12,
        'o', 14,
        '{', 18,
        '|', 19,
        '}', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 47,
        '"', 3,
        '\'', 5,
        '(', 51,
        '+', 39,
        '-', 40,
        '@', 59,
        'n', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 7,
        '%', 38,
        '&', 4,
        ')', 52,
        '*', 35,
        '+', 39,
        '-', 40,
        '/', 36,
        ':', 6,
        '<', 31,
        '=', 8,
        '>', 30,
        'a', 10,
        'i', 15,
        'o', 14,
        '|', 19,
        '}', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(60);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(43);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == '{') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == '|') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(27);
      END_STATE();
    case 21:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 24:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_isnot);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_is);
      if (lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__identifier_regexp);
      if (lookahead == 'o') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__identifier_regexp);
      if (lookahead == 't') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__identifier_regexp);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 21},
  [35] = {.lex_state = 21},
  [36] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_isnot] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(36),
    [sym__node] = STATE(32),
    [sym_expression_block] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_integer_literal,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(13), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(19), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [43] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(21), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(23), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [86] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(25), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(16), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [129] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(29), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(26), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [172] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(35), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(33), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(22), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [215] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(39), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(37), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(24), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [258] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(43), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(41), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(17), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [301] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(45), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(21), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [344] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(51), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(49), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(14), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [387] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(55), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(53), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(18), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [430] = 9,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym__identifier_regexp,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(59), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_namespace_name,
    ACTIONS(57), 2,
      sym_string_literal,
      sym_float_literal,
    ACTIONS(7), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(20), 13,
      sym__expression,
      sym__primary_expression,
      sym_binary_expression,
      sym_comparison_expression,
      sym_equality_expression,
      sym_identity_expression,
      sym_logical_expression,
      sym_unary_expression,
      sym_parenthesized_expression,
      sym__number_literal,
      sym__identifier,
      sym_user_identifier,
      sym_namespace_identifier,
  [473] = 4,
    ACTIONS(65), 1,
      anon_sym_COLON_COLON,
    STATE(27), 1,
      sym_namespace_value,
    ACTIONS(63), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(61), 16,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR_STAR,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [505] = 6,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(69), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_is,
    ACTIONS(67), 13,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [540] = 2,
    ACTIONS(79), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(77), 17,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR_STAR,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
      anon_sym_COLON_COLON,
  [567] = 3,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(83), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(81), 16,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR_STAR,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [596] = 4,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(69), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(67), 15,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [627] = 11,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    ACTIONS(95), 1,
      anon_sym_isnot,
    ACTIONS(97), 1,
      anon_sym_is,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(87), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(85), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [672] = 10,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    ACTIONS(101), 1,
      anon_sym_is,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(87), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(99), 7,
      anon_sym_RBRACE_RBRACE,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [715] = 12,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    ACTIONS(95), 1,
      anon_sym_isnot,
    ACTIONS(97), 1,
      anon_sym_is,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(87), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(85), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [762] = 4,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(69), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(67), 15,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [793] = 10,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    ACTIONS(107), 1,
      anon_sym_is,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(87), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(105), 7,
      anon_sym_RBRACE_RBRACE,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [836] = 7,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(111), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_is,
    ACTIONS(109), 11,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [873] = 13,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    ACTIONS(95), 1,
      anon_sym_isnot,
    ACTIONS(97), 1,
      anon_sym_is,
    ACTIONS(113), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(87), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(115), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
  [921] = 2,
    ACTIONS(119), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(117), 16,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR_STAR,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [947] = 13,
    ACTIONS(71), 1,
      anon_sym_STAR_STAR,
    ACTIONS(95), 1,
      anon_sym_isnot,
    ACTIONS(97), 1,
      anon_sym_is,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(3), 1,
      sym_comparison_operators,
    ACTIONS(73), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
    ACTIONS(87), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(115), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
  [995] = 2,
    ACTIONS(125), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(123), 16,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR_STAR,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [1021] = 2,
    ACTIONS(129), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(127), 16,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR_STAR,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [1047] = 2,
    ACTIONS(133), 5,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_is,
    ACTIONS(131), 16,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR_STAR,
      anon_sym_SLASH_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_isnot,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_RPAREN,
  [1073] = 2,
    ACTIONS(137), 3,
      anon_sym_not,
      sym_integer_literal,
      sym__identifier_regexp,
    ACTIONS(135), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LPAREN,
      sym_string_literal,
      sym_float_literal,
      anon_sym_AT,
  [1088] = 3,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(31), 3,
      sym__node,
      sym_expression_block,
      aux_sym_source_file_repeat1,
  [1100] = 3,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    STATE(31), 3,
      sym__node,
      sym_expression_block,
      aux_sym_source_file_repeat1,
  [1112] = 1,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
  [1117] = 1,
    ACTIONS(148), 1,
      sym__identifier_regexp,
  [1121] = 1,
    ACTIONS(150), 1,
      sym__identifier_regexp,
  [1125] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 172,
  [SMALL_STATE(7)] = 215,
  [SMALL_STATE(8)] = 258,
  [SMALL_STATE(9)] = 301,
  [SMALL_STATE(10)] = 344,
  [SMALL_STATE(11)] = 387,
  [SMALL_STATE(12)] = 430,
  [SMALL_STATE(13)] = 473,
  [SMALL_STATE(14)] = 505,
  [SMALL_STATE(15)] = 540,
  [SMALL_STATE(16)] = 567,
  [SMALL_STATE(17)] = 596,
  [SMALL_STATE(18)] = 627,
  [SMALL_STATE(19)] = 672,
  [SMALL_STATE(20)] = 715,
  [SMALL_STATE(21)] = 762,
  [SMALL_STATE(22)] = 793,
  [SMALL_STATE(23)] = 836,
  [SMALL_STATE(24)] = 873,
  [SMALL_STATE(25)] = 921,
  [SMALL_STATE(26)] = 947,
  [SMALL_STATE(27)] = 995,
  [SMALL_STATE(28)] = 1021,
  [SMALL_STATE(29)] = 1047,
  [SMALL_STATE(30)] = 1073,
  [SMALL_STATE(31)] = 1088,
  [SMALL_STATE(32)] = 1100,
  [SMALL_STATE(33)] = 1112,
  [SMALL_STATE(34)] = 1117,
  [SMALL_STATE(35)] = 1121,
  [SMALL_STATE(36)] = 1125,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_identifier, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace_identifier, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_name, 2, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace_name, 2, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_expression, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality_expression, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equality_expression, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identity_expression, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identity_expression, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_expression, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_expression, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_identifier, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user_identifier, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_identifier, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace_identifier, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_value, 2, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace_value, 2, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operators, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_operators, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_flow(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "flow",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
